src/main/java/ssginc_kdt_team3/BE/domain/Cust.java, src/main/java/ssginc_kdt_team3/BE/domain/Grade.java
=> cust modify

src/main/java/ssginc_kdt_team3/BE/BeApplication.java, src/main/java/ssginc_kdt_team3/BE/DTOs/admin/AdminLoginDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/cust/Address.java, src/main/java/ssginc_kdt_team3/BE/DTOs/cust/CustListDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/cust/CustUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/cust/Role.java, src/main/java/ssginc_kdt_team3/BE/SpringConfig.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminLoginController.java, src/main/java/ssginc_kdt_team3/BE/domain/Cust.java, src/main/java/ssginc_kdt_team3/BE/domain/Grade.java, src/main/java/ssginc_kdt_team3/BE/domain/OperationInfo.java, src/main/java/ssginc_kdt_team3/BE/domain/Owner.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/domain/Store.java, src/main/java/ssginc_kdt_team3/BE/enums/UserRole.java, src/main/java/ssginc_kdt_team3/BE/repository/admin/JpaDateAdminRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/cust/JpaDateCustRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminCustService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminService.java, src/main/resources/application.properties, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminCustServiceTest.java
=> update colum name and datatype

.github/workflows/deploy.yml
**작업 주제**
EC2 배포 설정 파일 수정했습니다
**작업 내용**
- github 배포에서 gradle build를 못하는 오류 수정했습니다
=> fix: aws 배포 설정 gradle부분 수정

src/main/java/ssginc_kdt_team3/BE/DTOs/cust/CustJoinDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/cust/CustController.java, src/main/java/ssginc_kdt_team3/BE/repository/cust/JpaCustRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/interfaces/cust/CustRepository.java, src/main/java/ssginc_kdt_team3/BE/service/cust/CustService.java, src/test/java/ssginc_kdt_team3/BE/service/cust/CustServiceTest.java
=> cust join, login

src/main/java/ssginc_kdt_team3/BE/DTOs/cust/CustDetailDTO.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminCustServiceTest.java
디테일 dto로 grade가 없어서 작동 안하는 테스트 문제 해결
=> update admin cust test

.github/workflows/deploy.yml
**작업 주제**
프로젝트를 build 할 시 gradle이 잡히지 않는 오류에 대한 수정입니다
**작업 내용**
GitHub 액션으로 배포할 때 'gradlew' 파일을 실행할 수 있도록 하려면 빌드 단계 전에 파일 권한을 수정하는 코드를 추가했습니다
=> fix: gradle 오류 수정

.github/workflows/deploy.yml
**작업 주제**
gradle build시 기본 test에서 일어나는 오류 수정입니다
**작업 내용**
gradle build 테스트 완료가 되지 않은 테스트 코드가 들어온 경우 build오류를 수정했습니다
=> fix: gradle test 오류 수정

.github/workflows/deploy.yml
**작업 주제** 
배포 파일의 access key, secret key 이름 수정입니다
**작업 내용**
access key와 secret key가 배포 설정 파일의 이름과 불일치해서 접속을 못하는 오류에 대한 수정입니다
=> fix: access key, secret ket id 이름 수정

build.gradle, src/main/java/ssginc_kdt_team3/BE/DTOs/cust/CustListDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/owner/ownerDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopListDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/SpringConfig.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Cust.java, src/main/java/ssginc_kdt_team3/BE/domain/Grade.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/domain/ShopOperationInfo.java, src/main/java/ssginc_kdt_team3/BE/domain/Store.java, src/main/java/ssginc_kdt_team3/BE/domain/StoreOperationInfo.java, src/main/java/ssginc_kdt_team3/BE/repository/cust/JpaDateCustRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/shop/JpaDateShopOperationInfoRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/shop/JpaDateShopRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminCustService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminShopService.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminCustServiceTest.java
admin shop list 조회,  shop detail 조회, update 작성
=> create shop feature

.github/workflows/gradle.yml
작업 주제
-------------
- ci 누락된 부분이 있어서 수정했습니다
작업 내용
-------------
- ci 누락된 부분을 추가했습니다
- 추가로 gradle 권한 오류에 대해서 수정했습니다 
- 브랜치 테스트 통과했으니 앞으로 dev 브랜치, feature 브랜치로 올리면 ci가 적용됩니다
=> [Feature-1] ci 추가

appspec.yml, scripts/start.sh, scripts/stop.sh
작업 주제
-------------
- AWS 자동 배포 스크립트의 일부 수정 및 추가 했습니다
작업 내용
-------------
-  AWS의 스크립트 파일을 프로젝트 내에 추가해야 CodeDeploy에 자동 배포 명령어를 실행할 수 있어서 추가했습니다
=> chore: AWS 배포 스크립트 파일 수정 및 추가

src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerFindPwService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerJoinService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerUpdateService.java
=> 도메인 변경후 owner코드 수정

src/main/java/ssginc_kdt_team3/BE/domain/Alarm.java, src/main/java/ssginc_kdt_team3/BE/domain/Coupon.java, src/main/java/ssginc_kdt_team3/BE/domain/CouponManage.java, src/main/java/ssginc_kdt_team3/BE/domain/CouponProvide.java, src/main/java/ssginc_kdt_team3/BE/domain/Deposit.java, src/main/java/ssginc_kdt_team3/BE/domain/Reservation.java, src/main/java/ssginc_kdt_team3/BE/domain/Review.java, src/main/java/ssginc_kdt_team3/BE/enums/CouponManageType.java, src/main/java/ssginc_kdt_team3/BE/enums/CouponStatus.java, src/main/java/ssginc_kdt_team3/BE/enums/ReviewStatus.java
=> add domain

build.gradle, src/main/java/ssginc_kdt_team3/BE/DTOs/deposit/AdminDepositDTO.java, src/main/java/ssginc_kdt_team3/BE/domain/Deposit.java, src/main/java/ssginc_kdt_team3/BE/enums/DepositStatus.java, src/main/java/ssginc_kdt_team3/BE/enums/ReservationStatus.java, src/main/java/ssginc_kdt_team3/BE/repository/deposit/AdminDepositRepository.java, src/test/java/ssginc_kdt_team3/BE/repository/deposit/AdminDepositRepositoryTest.java
관리자 shop id를 통한 deposit_list 조회
=> create deposit_list reposiory

src/main/java/ssginc_kdt_team3/BE/DTOs/deposit/AdminDepositDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminDepositController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/repository/deposit/AdminDepositRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminDepositService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminOwnerService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerChangePwService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerLoginService.java, src/test/java/ssginc_kdt_team3/BE/repository/deposit/AdminDepositRepositoryTest.java
=> create show deposit list

src/main/java/ssginc_kdt_team3/BE/DTOs/deposit/AdminDepositDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationAddDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminDepositService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/test/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationServiceTest.java
=> Customer reservation

src/main/java/ssginc_kdt_team3/BE/DTOs/admin/AdminLoginDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerChangePwController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/repository/deposit/AdminDepositRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/deposit/OwnerDepositRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/shop/JpaDateShopRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminShopService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/service/Owner/OwnerReservationServiceTest.java
=> create reservation customer list

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationAddDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminDepositController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/test/java/ssginc_kdt_team3/BE/service/Owner/OwnerReservationServiceTest.java, src/test/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationServiceTest.java
=> create customer reservation update

src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/service/Owner/OwnerReservationServiceTest.java
=> create owner reservation reject

src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java
점주가 예약 취소,노쇼,입장 처리할 때 db의 변경시간 바뀌도록 수정
=> Owner reservation update

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/util/TimeUtils.java
=> create customer reservation detail

src/main/java/ssginc_kdt_team3/BE/DTOs/shop/CustomerShopListDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchController.java, src/main/java/ssginc_kdt_team3/BE/repository/branch/JpaDataBranchRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/shop/JpaShopRepository.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/reservation/OwnerReserveService.java
=> create customer shop list

src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerUpdateInfoController.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepositoryTest.java, src/test/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationServiceTest.java
=> create reserve possible and fix typo

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java
=> update customer check can reserve

src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java
=> fix canReserve - id

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/reserve/ReserveController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java
오늘 이전의 시간 or 정책상 예약 가능 기한보다 더 먼날은 무조건 불가능으로 처리
=> update canReserve limit day

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationUpdateDTO.java
=> add shop id

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminReservationController.java
=> request body -> requestParam

src/main/java/ssginc_kdt_team3/BE/DTOs/deposit/OwnerDepositDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/OwnerReservationDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerDepositController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/OwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/KakaoService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerDepositService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/reservation/OwnerReserveService.java
=> owner Deposit

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCustomerController.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/resources/application.properties
=> add pageSize

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/OwnerReservationDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/service/owner/reservation/OwnerReserveService.java, src/main/resources/application.properties
점주 모든 예약정보 가져오기 -> ownerId로 shop 정보 찾아오기 추가
=> modify getAllReserve Service

src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReservationController.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/OwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerDepositService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/reservation/OwnerReserveService.java, src/test/java/ssginc_kdt_team3/BE/repository/owner/reservation/OwnerRepositoryTest.java
예약조회 필터링 부분 -> shopid 추가 및 페이징처리
=> add shopId, paging

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java
=> update login for middle present

src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerController.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerLoginService.java
=> for middle present temp owner login

src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopMenuDto.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/repository/shop/JpaDataShopRepository.java, src/main/java/ssginc_kdt_team3/BE/service/Shop/ShopDetailService.java
=> replace shop detail

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/repository/review/JpaDataReviewRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java
=> update customerReservationDetail - canReview

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/ReviewDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReviewController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java
=> customer addReview

build.gradle, src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchAddDTO.java, src/main/java/ssginc_kdt_team3/BE/S3Config.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchController.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Branch.java, src/main/java/ssginc_kdt_team3/BE/domain/BranchOperationInfo.java, src/main/java/ssginc_kdt_team3/BE/repository/branch/JpaDataBranchInfoRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/branch/JpaDataBranchRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/review/JpaDataReviewRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminBranchService.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchService.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchShopListService.java, src/main/java/ssginc_kdt_team3/BE/util/FileUploadUtil.java, src/main/java/ssginc_kdt_team3/BE/util/TimeUtils.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminBranchServiceTest.java, src/test/java/ssginc_kdt_team3/BE/util/TimeUtilsTest.java
=> admin create branch

src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchAddDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminBranchService.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminBranchServiceTest.java
=> add branch multipartfile upload

src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/domain/Branch.java, src/main/java/ssginc_kdt_team3/BE/domain/BranchOperationInfo.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminBranchService.java
=> create admin Branch delete and update

src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchAdminListDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminBranchService.java
=> create admin branch list

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerDataController.java
https://www.notion.so/owner-update-info-id-POST-cba4ee19d92142619a42595763ffc1a6
=> Owner- OwnerDataController Bug Fix - Update 

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Branch.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminBranchService.java
=> Admin - branch update img - Update

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminBranchController.java
=> admin - branch update mapping update (post -> put) - update

src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchShopDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/AdminShopUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/domain/ShopOperationInfo.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminShopService.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerShopService.java, src/main/java/ssginc_kdt_team3/BE/service/shop/ShopDetailReviewService.java
=> create : owner_shop update

src/main/java/ssginc_kdt_team3/BE/DTOs/shop/AdminShopDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminShopController.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminShopService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerShopService.java
관리자 매장 상세 조회 기능 추가
API : https://www.notion.so/owner-shop-detail-id-GET-ff36b2981d4d419c8eb50168154e4f78
=> create : admin_show Shop detail

src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/branch/BranchShopDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/repository/branch/BranchRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/branch/BranchOwnerService.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchShopListService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerViewSelfPrivacyService.java
점주 - 점주 상세정보 조회 API : https://www.notion.so/owner-detail-id-GET-1aa42ead360b4f07845e172a1c3e7dc9
점주 - 점주 정보 수정 API : https://www.notion.so/owner-update-info-id-POST-cba4ee19d92142619a42595763ffc1a6
관리자 - 지점별 조회 API : https://www.notion.so/admin-owner-findAll-id-page-GET-e7316997d4c643308e07c62c95a00963
관리자 - 점주 상세정보 조회 API : https://www.notion.so/admin-owner-findOne-id-GET-78b6832efccb406d9eb9c740044c3c28
고객 - 지점별 매장 조회 API : https://www.notion.so/shop-list-id-o-699f2d2cd6384b238df68d99bee462c3
=> Update : [owner : ownerDetail&ownerUpdate] - [admin : adminOwnerDetail&adminBranchOwnerList] - [customer : customerBranchShopList] 

src/main/java/ssginc_kdt_team3/BE/DTOs/menu/MenuAddDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerMenuController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerShopController.java, src/main/java/ssginc_kdt_team3/BE/domain/ShopMenu.java, src/main/java/ssginc_kdt_team3/BE/service/menu/OwnerMenuService.java, src/main/java/ssginc_kdt_team3/BE/service/shop/OwnerShopService.java, src/main/resources/application.properties
점주 매장 신규 메뉴 등록 기능 추가
API : https://www.notion.so/owner-menu-add-POST-7f4dda9f7b35410eb24b0360ee6a8c4c
=> Owner menu

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminOwnerController.java, src/main/java/ssginc_kdt_team3/BE/repository/customer/JpaDataCustomerRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminOwnerService.java, src/main/java/ssginc_kdt_team3/BE/service/branch/BranchShopListService.java
API : https://www.notion.so/admin-owner-delete-id-Delete-78d2ffafdabf4fe0aa8005eb6684ed7a
=> create : owner_delete

src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/domain/Shop.java, src/main/java/ssginc_kdt_team3/BE/repository/shop/JpaDataShopRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminShopService.java, src/main/java/ssginc_kdt_team3/BE/service/shop/ShopDetailService.java
=> update : show admin_shopList error fix

src/main/java/ssginc_kdt_team3/BE/DTOs/admin/AdminBranchOwnerDTO.java, src/main/java/ssginc_kdt_team3/BE/repository/customer/JpaDataCustomerRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java
지점별 점주 목록 조회(필터) : https://www.notion.so/admin-owner-findAll-id-page-GET-e7316997d4c643308e07c62c95a00963
고객 지점별 매장목록 조회 : https://www.notion.so/shop-list-id-o-699f2d2cd6384b238df68d99bee462c3
=> update : Customer_Branch_shop list & AdminBranchOwner list

src/main/java/ssginc_kdt_team3/BE/DTOs/menu/MenuUpdateDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerMenuController.java, src/main/java/ssginc_kdt_team3/BE/domain/ShopMenu.java, src/main/java/ssginc_kdt_team3/BE/service/menu/OwnerMenuService.java
오너 메뉴 삭제 및 수정
API :  https://www.notion.so/owner-menu-delete-id-Delete-c45721bbff0d4045bc58db5cc043f78c
=> create : owner_menu update and delete

src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminReservationController.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminReservationService.java
점주 예약 목록 페이지로 변경|
https://www.notion.so/ae62138c0e1d407b8832a52662ba415d
=> update : adminReservatinList_List -> Page

src/main/java/ssginc_kdt_team3/BE/DTOs/owner/OwnerJoinDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerShopController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerJoinService.java
=> update : customer address db save, owner shop add ment

src/main/java/ssginc_kdt_team3/BE/DTOs/owner/OwnerReviewListDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminReviewController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReviewController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReviewController.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/review/JpaDataReviewRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReviewService.java
점주&고객 : 후기목록 조회 필터기능 구현
1) 점주: https://www.notion.so/9b7eda2c8ba64f9abb806405ca26310a
2) 고객: https://www.notion.so/3b5b7b99ad6443c2b9b75cbf33bc09be
=> create : owner_showReviewList, and customer_showReviewList

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerFindDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/customer/ReviewResponseDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/repository/customer/JpaDataCustomerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java
고객 이메일, 비밀번호 찾기 기능에 name 검증 추가
이메일 찾기: https://www.notion.so/8fc778e2b0774764abf36709dde4e008
비밀번호 찾기: https://www.notion.so/fbc37eb057d34bb3b774b968b258c824
=> update : customer_add name to InfoSearchFunction

src/main/java/ssginc_kdt_team3/BE/DTOs/kakao/Amount.java, src/main/java/ssginc_kdt_team3/BE/DTOs/kakao/KakaoPayApproveResponseDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/kakao/KakaoPayReadyResponseDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/kakao/KakaoRefundResponseDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/exception/BusinessLogicException.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java, src/main/resources/application.properties, src/main/resources/static/home.html
유저 카카오 페이를 이용한 결제 기능 구현 (아직 충전금 충전은 안됨)
API : https://www.notion.so/customer-charge-de6ec898e7044188bad201c65e41ece5
=> create : customer_kakaoPay

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/EmailFindDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/customer/PasswordFindDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java, src/test/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepositoryTest.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminReservationServiceTest.java
shopDetailDto 수정, customerController 이메일, 비밀번호 찾기 RequestBody로 수정
=> update : customer_modify  cusomerController and dto etc

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/domain/ChargingDetail.java, src/main/java/ssginc_kdt_team3/BE/domain/ChargingManagement.java, src/main/java/ssginc_kdt_team3/BE/domain/PaymentManaging.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingDetailRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingManagementRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/payManaging/JpaDataPayManagingRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java, src/test/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingDetailRepositoryTest.java, src/test/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepositoryTest.java, src/test/java/ssginc_kdt_team3/BE/service/admin/AdminReservationServiceTest.java
=> create : customer_charging via kakaoPay

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReviewController.java, src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReviewController.java, src/main/java/ssginc_kdt_team3/BE/repository/owner/JpaDataOwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/review/JpaDataReviewRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReviewService.java
점주: 후기목록 조회 필터기능 구현
https://www.notion.so/9b7eda2c8ba64f9abb806405ca26310a
=> Review list

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerChargeDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerChargingListDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/kakao/KakaoPayApproveResponseDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/OwnerShopDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingDetailRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingManagementRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerChargingService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java
=> Customer charge

src/main/java/ssginc_kdt_team3/BE/domain/Grade.java
=> update : grade_domain add column

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerChargingListDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingManagementRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerChargingService.java
수정 : 유저 충전 목록 날짜 
api : https://www.notion.so/customer-charge-list-id-type-date-page-6f15c14f365e4ac3a08c7c834aee6275
=> update : customer_chartgeList add date filter and dto - type

src/main/java/ssginc_kdt_team3/BE/DTOs/coupon/CreateCouponDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminCouponController.java, src/main/java/ssginc_kdt_team3/BE/controller/admin/AdminGradeController.java, src/main/java/ssginc_kdt_team3/BE/domain/CouponManage.java, src/main/java/ssginc_kdt_team3/BE/repository/coupon/CouponManageRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/coupon/CouponRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/grade/GradeRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminGradeService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/CouponManagementService.java
관리자 쿠폰 생성
https://www.notion.so/223468a7c7094ca98943806f5ad85c5b
=> create : admin_addCoupon

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java, src/main/java/ssginc_kdt_team3/BE/enums/DepositStatus.java, src/main/java/ssginc_kdt_team3/BE/service/chargingManagement/ChargingManagementService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/resources/application.properties, src/test/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationServiceTest.java
고객 예약정보 업데이트 시 예약금 환불, 추가 지급 기능 추가
=> create : customer reservation update payment

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerChargingListDTO.java, src/main/java/ssginc_kdt_team3/BE/domain/PointManagement.java, src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingDetailRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/point/JpaDataPointDetailRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/point/JpaDataPointManagementRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerChargingService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/pointManagement/PointManagementService.java, src/main/resources/application.properties
=> update : check can refund

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationAddDTO.java
=> chore : point bug fix

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerController.java, src/main/java/ssginc_kdt_team3/BE/exception/ErrorResponse.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerService.java
고객 회원가입, 중복이메일 검증 컨트롤러 수정 - Validation 추가
https://www.notion.so/9d252e0544c54302bf75d32162c53e9c
=> update : customer_addValidation join and emailCheck

src/main/java/ssginc_kdt_team3/BE/scheduler/GradeScheduler.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerGradeService.java
=> chore : customer_packageChange

src/main/java/ssginc_kdt_team3/BE/controller/owner/OwnerReviewController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerGradeService.java
고객 등급변동 조건 수정
기존 10회, 5회 이상 충족 -> DB의 gradeRequirement 값으로 변경
=> update : customer_modifiedGradeCondition

src/main/java/ssginc_kdt_team3/BE/DTOs/customer/CustomerPersonalizeShopDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/shop/ShopAddDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/branch/BranchShopController.java, src/main/java/ssginc_kdt_team3/BE/repository/customer/JpaDataCustomerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerPersonalizeShopService.java
API : https://www.notion.so/0520618218c74c50bdb854dd2a071ea3
=> update : suggestionShopSystem

src/main/java/ssginc_kdt_team3/BE/DTOs/event/BannerDTO.java, src/main/java/ssginc_kdt_team3/BE/DTOs/event/EventDetailDTO.java, src/main/java/ssginc_kdt_team3/BE/controller/event/EventController.java, src/main/java/ssginc_kdt_team3/BE/domain/Event.java, src/main/java/ssginc_kdt_team3/BE/enums/EventStatus.java, src/main/java/ssginc_kdt_team3/BE/repository/event/EventRepository.java, src/main/java/ssginc_kdt_team3/BE/service/event/EventService.java
이벤트 배너 호출 및 이벤트 상세 확인 기능 추가
DB변동
=> create : event Banner DB, mainPage banner, detail

src/main/java/ssginc_kdt_team3/BE/DTOs/event/BannerDTO.java
=> update bannerDTO , date title branchName

src/main/java/ssginc_kdt_team3/BE/DTOs/shop/OwnerShopDetailDTO.java
=> chore : owner shop detail category null bug fix

src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java
=> resolve : Datetimeformatter

src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/util/service/reservation/Owner/OwnerReservationServiceTest.java
=> update ownerMain daily rate 0 bug

src/main/java/ssginc_kdt_team3/BE/repository/charging/JpaDataChargingDetailRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/coupon/CouponProvideRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/deposit/DepositRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/review/JpaDataReviewRepository.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/admin/AdminReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerCouponService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReviewService.java, src/main/java/ssginc_kdt_team3/BE/service/shop/ShopDetailReviewService.java, src/test/java/ssginc_kdt_team3/BE/repository/coupon/CouponProvideRepositoryTest.java
=> update all list order desc

src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/resources/application.properties
=> chore customer reservation list desc

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/OwnerReservationDTO.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/repository/reservation/OwnerRepository.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java
점주 전체 예약 목록 불러오기 수정
활성화 예약 목록 조회 수정
=> update owner Reservation List

src/main/java/ssginc_kdt_team3/BE/repository/reservation/JpaDataReservationRepository.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java
=> update owner resevation page

src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerPersonalizeShopService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/repository/customer/CustomerReservationServiceTest.java, src/test/java/ssginc_kdt_team3/BE/service/alarmServiceTest.java
resolve : personalize & DateTypeFormatter
=> resolve : personalize & DateTypeFormatter

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/Alarm/MessageDTO.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerReservationService.java, src/main/java/ssginc_kdt_team3/BE/service/customer/NaverAlarmService.java, src/main/java/ssginc_kdt_team3/BE/service/owner/OwnerReservationService.java, src/test/java/ssginc_kdt_team3/BE/service/alarmServiceTest.java
=> update : Lms&Sms service

src/main/java/ssginc_kdt_team3/BE/DTOs/reservation/CustomerReservationAddDTO.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java, src/main/resources/application.properties
=> Customer point

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerReservationController.java
=> chore reservation message update

src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java
=> update kakao url distribution

src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java
=> update controller url

src/main/java/ssginc_kdt_team3/BE/BeApplication.java, src/main/java/ssginc_kdt_team3/BE/WebConfig.java, src/main/java/ssginc_kdt_team3/BE/controller/customer/CustomerChargeController.java, src/main/java/ssginc_kdt_team3/BE/service/customer/CustomerKakaoPayService.java
=> update redirect url
